INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('ADMIN', 'Administrador del sistema');
INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('USER', 'Usuario estándar del sistema');
INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('LAB_TECH', 'Técnico de laboratorio');

INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('PENDIENTE');
INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('EN PROCESO');
INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('FINALIZADO');
INSERT INTO ANALYSIS_STATUS (DESCRIPTION) VALUES ('CANCELADO');

